[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
# Admin can do anything.
# Otherwise, user's sub must match the policy sub, and obj and act must match.
m = r.sub == "admin" || (r.sub == p.sub && r.obj == p.obj && r.act == p.act)
